name: tractian
description: "TRACTIAN Challenge."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  oktoast: ^3.4.0
  dio: ^5.7.0
  get_it: ^8.0.0
  either_dart: ^1.0.0
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true